/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"

	apicustomboardv1alpha1 "github.com/kyverno/policy-reporter-ui/pkg/crd/api/customboard/v1alpha1"
	versioned "github.com/kyverno/policy-reporter-ui/pkg/crd/client/clientset/versioned"
	internalinterfaces "github.com/kyverno/policy-reporter-ui/pkg/crd/client/informers/externalversions/internalinterfaces"
	customboardv1alpha1 "github.com/kyverno/policy-reporter-ui/pkg/crd/client/listers/customboard/v1alpha1"
)

// CustomBoardInformer provides access to a shared informer and lister for
// CustomBoards.
type CustomBoardInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() customboardv1alpha1.CustomBoardLister
}

type customBoardInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCustomBoardInformer constructs a new informer for CustomBoard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCustomBoardInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCustomBoardInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredCustomBoardInformer constructs a new informer for CustomBoard type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCustomBoardInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UiV1alpha1().CustomBoards().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UiV1alpha1().CustomBoards().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UiV1alpha1().CustomBoards().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UiV1alpha1().CustomBoards().Watch(ctx, options)
			},
		},
		&apicustomboardv1alpha1.CustomBoard{},
		resyncPeriod,
		indexers,
	)
}

func (f *customBoardInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCustomBoardInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *customBoardInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apicustomboardv1alpha1.CustomBoard{}, f.defaultInformer)
}

func (f *customBoardInformer) Lister() customboardv1alpha1.CustomBoardLister {
	return customboardv1alpha1.NewCustomBoardLister(f.Informer().GetIndexer())
}
