export const APIFilter = Symbol('default filter for dashboard  resources')
export const ShowedStatus = Symbol('show status chip')
export const NamespacedKinds = Symbol('namespaced kind filters')
export const ClusterKinds = Symbol('cluster kind filters')
export const SourceContext = Symbol('source context')
