/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"

	customboardv1alpha1 "github.com/kyverno/policy-reporter-ui/pkg/crd/api/customboard/v1alpha1"
)

// CustomBoardLister helps list CustomBoards.
// All objects returned here must be treated as read-only.
type CustomBoardLister interface {
	// List lists all CustomBoards in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*customboardv1alpha1.CustomBoard, err error)
	// Get retrieves the CustomBoard from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*customboardv1alpha1.CustomBoard, error)
	CustomBoardListerExpansion
}

// customBoardLister implements the CustomBoardLister interface.
type customBoardLister struct {
	listers.ResourceIndexer[*customboardv1alpha1.CustomBoard]
}

// NewCustomBoardLister returns a new CustomBoardLister.
func NewCustomBoardLister(indexer cache.Indexer) CustomBoardLister {
	return &customBoardLister{listers.New[*customboardv1alpha1.CustomBoard](indexer, customboardv1alpha1.Resource("customboard"))}
}
