/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"

	customboardv1alpha1 "github.com/kyverno/policy-reporter-ui/pkg/crd/api/customboard/v1alpha1"
)

// NamespaceCustomBoardLister helps list NamespaceCustomBoards.
// All objects returned here must be treated as read-only.
type NamespaceCustomBoardLister interface {
	// List lists all NamespaceCustomBoards in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*customboardv1alpha1.NamespaceCustomBoard, err error)
	// NamespaceCustomBoards returns an object that can list and get NamespaceCustomBoards.
	NamespaceCustomBoards(namespace string) NamespaceCustomBoardNamespaceLister
	NamespaceCustomBoardListerExpansion
}

// namespaceCustomBoardLister implements the NamespaceCustomBoardLister interface.
type namespaceCustomBoardLister struct {
	listers.ResourceIndexer[*customboardv1alpha1.NamespaceCustomBoard]
}

// NewNamespaceCustomBoardLister returns a new NamespaceCustomBoardLister.
func NewNamespaceCustomBoardLister(indexer cache.Indexer) NamespaceCustomBoardLister {
	return &namespaceCustomBoardLister{listers.New[*customboardv1alpha1.NamespaceCustomBoard](indexer, customboardv1alpha1.Resource("namespacecustomboard"))}
}

// NamespaceCustomBoards returns an object that can list and get NamespaceCustomBoards.
func (s *namespaceCustomBoardLister) NamespaceCustomBoards(namespace string) NamespaceCustomBoardNamespaceLister {
	return namespaceCustomBoardNamespaceLister{listers.NewNamespaced[*customboardv1alpha1.NamespaceCustomBoard](s.ResourceIndexer, namespace)}
}

// NamespaceCustomBoardNamespaceLister helps list and get NamespaceCustomBoards.
// All objects returned here must be treated as read-only.
type NamespaceCustomBoardNamespaceLister interface {
	// List lists all NamespaceCustomBoards in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*customboardv1alpha1.NamespaceCustomBoard, err error)
	// Get retrieves the NamespaceCustomBoard from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*customboardv1alpha1.NamespaceCustomBoard, error)
	NamespaceCustomBoardNamespaceListerExpansion
}

// namespaceCustomBoardNamespaceLister implements the NamespaceCustomBoardNamespaceLister
// interface.
type namespaceCustomBoardNamespaceLister struct {
	listers.ResourceIndexer[*customboardv1alpha1.NamespaceCustomBoard]
}
